# Generated by Django 4.1.12 on 2025-11-22 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reference", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "publisher_meta",
                    models.JSONField(
                        null=True, verbose_name="JSON данные запроса на публикацию"
                    ),
                ),
                (
                    "publisher_status",
                    models.IntegerField(
                        choices=[(0, "Ошибка"), (1, "Успешно"), (2, "Обработка")],
                        null=True,
                        verbose_name="[ИС] Статус обработки",
                    ),
                ),
                (
                    "publisher_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата обработки публикации"
                    ),
                ),
                (
                    "service_meta",
                    models.JSONField(
                        null=True, verbose_name="JSON данные запроса в сервис"
                    ),
                ),
                (
                    "service_response",
                    models.JSONField(
                        null=True, verbose_name="JSON данные ответа сервиса"
                    ),
                ),
                (
                    "service_response_code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Код ответа сервиса"
                    ),
                ),
                (
                    "service_status",
                    models.IntegerField(
                        choices=[(0, "Ошибка"), (1, "Успешно"), (2, "Обработка")],
                        null=True,
                        verbose_name="[СП] Статус публикации",
                    ),
                ),
                (
                    "service_publish_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата публикации в сервис"
                    ),
                ),
                (
                    "service_item_link",
                    models.URLField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="Ссылка на опубликованный объект в сервисе",
                    ),
                ),
                (
                    "log",
                    models.TextField(
                        blank=True, null=True, verbose_name="Лог обработки задачи"
                    ),
                ),
                (
                    "last_log",
                    models.TextField(
                        blank=True, null=True, verbose_name="Послелняя строка лога"
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0, verbose_name="Прогресс выполнения в процентах"
                    ),
                ),
                (
                    "total_tasks",
                    models.IntegerField(
                        default=0, verbose_name="Общее число этапов выполнения задачи"
                    ),
                ),
                (
                    "current_task",
                    models.IntegerField(
                        default=0, verbose_name="Текущий этапов выполнения задачи"
                    ),
                ),
                (
                    "error_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Описание ошибки"
                    ),
                ),
                (
                    "uploaded_files",
                    models.IntegerField(
                        default=0, verbose_name="Загружено файлов в S3"
                    ),
                ),
                (
                    "total_files",
                    models.IntegerField(
                        default=0, verbose_name="Всего файлов для загрузки в S3"
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Контекст выполнения задачи"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="reference.sourcecontentmap",
                        verbose_name="Целевой сервис",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reference.source",
                        verbose_name="Издательская система",
                    ),
                ),
            ],
            options={
                "verbose_name": "Задание на публикацию",
                "verbose_name_plural": "Задания на публикацию",
            },
        ),
        migrations.CreateModel(
            name="ContentItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "meta",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Метаданные пакета"
                    ),
                ),
                (
                    "internal_meta",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Метаданные внутри пакета"
                    ),
                ),
                (
                    "storage",
                    models.URLField(
                        blank=True,
                        max_length=4096,
                        null=True,
                        verbose_name="Путь к папке хранилища",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=1024,
                        null=True,
                        verbose_name="SKU",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        blank=True, db_index=True, null=True, verbose_name="Год издания"
                    ),
                ),
                (
                    "cover",
                    models.URLField(
                        blank=True,
                        max_length=4096,
                        null=True,
                        verbose_name="Путь к обложке",
                    ),
                ),
                (
                    "offline",
                    models.URLField(
                        blank=True,
                        max_length=4096,
                        null=True,
                        verbose_name="Путь к offline архиву",
                    ),
                ),
                (
                    "offline_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Размер офлайн пакета"
                    ),
                ),
                (
                    "start_file",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Стартовый файл",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reference.source",
                        verbose_name="Издательская система",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="core.task",
                        verbose_name="Задача на публикацию",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reference.sourcecontentmap",
                        verbose_name="Тип контента",
                    ),
                ),
            ],
            options={
                "verbose_name": "Единица контента",
                "verbose_name_plural": "Единицы контента",
            },
        ),
    ]
