# Generated by Django 5.1.3 on 2025-11-23 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("reference", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "publisher_meta",
                    models.JSONField(
                        null=True, verbose_name="Publication Request JSON Data"
                    ),
                ),
                (
                    "publisher_status",
                    models.IntegerField(
                        choices=[(0, "Error"), (1, "Success"), (2, "Processing")],
                        null=True,
                        verbose_name="[SS] Processing Status",
                    ),
                ),
                (
                    "publisher_date",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Publication Processing Date",
                    ),
                ),
                (
                    "service_meta",
                    models.JSONField(
                        null=True, verbose_name="Service Request JSON Data"
                    ),
                ),
                (
                    "service_response",
                    models.JSONField(
                        null=True, verbose_name="Service Response JSON Data"
                    ),
                ),
                (
                    "service_response_code",
                    models.IntegerField(
                        blank=True, null=True, verbose_name="Service Response Code"
                    ),
                ),
                (
                    "service_status",
                    models.IntegerField(
                        choices=[(0, "Error"), (1, "Success"), (2, "Processing")],
                        null=True,
                        verbose_name="[PS] Publication Status",
                    ),
                ),
                (
                    "service_publish_date",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Service Publication Date"
                    ),
                ),
                (
                    "service_item_link",
                    models.URLField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        verbose_name="Link to Published Item in Service",
                    ),
                ),
                (
                    "log",
                    models.TextField(
                        blank=True, null=True, verbose_name="Task Processing Log"
                    ),
                ),
                (
                    "last_log",
                    models.TextField(
                        blank=True, null=True, verbose_name="Last Log Line"
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(default=0, verbose_name="Progress in Percent"),
                ),
                (
                    "total_tasks",
                    models.IntegerField(
                        default=0, verbose_name="Total Task Execution Stages"
                    ),
                ),
                (
                    "current_task",
                    models.IntegerField(
                        default=0, verbose_name="Current Task Execution Stage"
                    ),
                ),
                (
                    "error_description",
                    models.TextField(
                        blank=True, null=True, verbose_name="Error Description"
                    ),
                ),
                (
                    "uploaded_files",
                    models.IntegerField(default=0, verbose_name="Files Uploaded to S3"),
                ),
                (
                    "total_files",
                    models.IntegerField(
                        default=0, verbose_name="Total Files to Upload to S3"
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Task Execution Context"
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="reference.datatype",
                        verbose_name="Target Service",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reference.source",
                        verbose_name="Source System",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
            },
        ),
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("postgres", "PostgreSQL"), ("duckdb", "DuckDB")],
                        default="postgres",
                        max_length=50,
                        verbose_name="Type",
                    ),
                ),
                (
                    "connection",
                    models.CharField(
                        max_length=2048, null=True, verbose_name="Connection String"
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="datasources",
                        to="core.task",
                        verbose_name="Task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Source",
                "verbose_name_plural": "Data Sources",
            },
        ),
        migrations.CreateModel(
            name="DataItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created", models.DateTimeField(auto_now_add=True)),
                (
                    "meta",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Package Metadata"
                    ),
                ),
                (
                    "internal_meta",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Internal Package Metadata"
                    ),
                ),
                (
                    "storage",
                    models.URLField(
                        blank=True,
                        max_length=4096,
                        null=True,
                        verbose_name="Storage Folder Path",
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=1024,
                        null=True,
                        verbose_name="SKU",
                    ),
                ),
                (
                    "year",
                    models.IntegerField(
                        blank=True,
                        db_index=True,
                        null=True,
                        verbose_name="Year of Publication",
                    ),
                ),
                (
                    "cover",
                    models.URLField(
                        blank=True,
                        max_length=4096,
                        null=True,
                        verbose_name="Cover Path",
                    ),
                ),
                (
                    "offline",
                    models.URLField(
                        blank=True,
                        max_length=4096,
                        null=True,
                        verbose_name="Offline Archive Path",
                    ),
                ),
                (
                    "offline_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="Offline Package Size"
                    ),
                ),
                (
                    "start_file",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Start File",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reference.source",
                        verbose_name="Source System",
                    ),
                ),
                (
                    "type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="reference.datatype",
                        verbose_name="Content Type",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="items",
                        to="core.task",
                        verbose_name="Publication Task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Item",
                "verbose_name_plural": "Data Items",
            },
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        max_length=2048, null=True, verbose_name="Webhook URL"
                    ),
                ),
                (
                    "jwt_secret",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="JWT Secret",
                    ),
                ),
                (
                    "aud",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="AUD"
                    ),
                ),
                (
                    "ttl",
                    models.IntegerField(default=3600, verbose_name="JWT TTL (seconds)"),
                ),
                (
                    "consumer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reference.consumer",
                        verbose_name="Consumer",
                    ),
                ),
                (
                    "task",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="webhooks",
                        to="core.task",
                        verbose_name="Task",
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook",
                "verbose_name_plural": "Webhooks",
            },
        ),
    ]
