# Generated by Django 4.1.12 on 2025-11-22 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0001_initial"),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contentitem",
            options={
                "verbose_name": "Content Item",
                "verbose_name_plural": "Content Items",
            },
        ),
        migrations.AlterModelOptions(
            name="task",
            options={
                "verbose_name": "Publication Task",
                "verbose_name_plural": "Publication Tasks",
            },
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="cover",
            field=models.URLField(
                blank=True, max_length=4096, null=True, verbose_name="Cover Path"
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="internal_meta",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Internal Package Metadata"
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="meta",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Package Metadata"
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="offline",
            field=models.URLField(
                blank=True,
                max_length=4096,
                null=True,
                verbose_name="Offline Archive Path",
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="offline_size",
            field=models.BigIntegerField(
                blank=True, null=True, verbose_name="Offline Package Size"
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reference.source",
                verbose_name="Source System",
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="start_file",
            field=models.CharField(
                blank=True, max_length=1024, null=True, verbose_name="Start File"
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="storage",
            field=models.URLField(
                blank=True,
                max_length=4096,
                null=True,
                verbose_name="Storage Folder Path",
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="task",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="items",
                to="core.task",
                verbose_name="Publication Task",
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="reference.sourcecontentmap",
                verbose_name="Content Type",
            ),
        ),
        migrations.AlterField(
            model_name="contentitem",
            name="year",
            field=models.IntegerField(
                blank=True, db_index=True, null=True, verbose_name="Year of Publication"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="context",
            field=models.JSONField(
                blank=True, null=True, verbose_name="Task Execution Context"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="current_task",
            field=models.IntegerField(
                default=0, verbose_name="Current Task Execution Stage"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="error_description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Error Description"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="last_log",
            field=models.TextField(blank=True, null=True, verbose_name="Last Log Line"),
        ),
        migrations.AlterField(
            model_name="task",
            name="log",
            field=models.TextField(
                blank=True, null=True, verbose_name="Task Processing Log"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="progress",
            field=models.IntegerField(default=0, verbose_name="Progress in Percent"),
        ),
        migrations.AlterField(
            model_name="task",
            name="publisher_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Publication Processing Date"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="publisher_meta",
            field=models.JSONField(
                null=True, verbose_name="Publication Request JSON Data"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="publisher_status",
            field=models.IntegerField(
                choices=[(0, "Error"), (1, "Success"), (2, "Processing")],
                null=True,
                verbose_name="[SS] Processing Status",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tasks",
                to="reference.sourcecontentmap",
                verbose_name="Target Service",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="service_item_link",
            field=models.URLField(
                blank=True,
                max_length=2048,
                null=True,
                verbose_name="Link to Published Item in Service",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="service_meta",
            field=models.JSONField(null=True, verbose_name="Service Request JSON Data"),
        ),
        migrations.AlterField(
            model_name="task",
            name="service_publish_date",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Service Publication Date"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="service_response",
            field=models.JSONField(
                null=True, verbose_name="Service Response JSON Data"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="service_response_code",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Service Response Code"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="service_status",
            field=models.IntegerField(
                choices=[(0, "Error"), (1, "Success"), (2, "Processing")],
                null=True,
                verbose_name="[PS] Publication Status",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="source",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reference.source",
                verbose_name="Source System",
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="total_files",
            field=models.IntegerField(
                default=0, verbose_name="Total Files to Upload to S3"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="total_tasks",
            field=models.IntegerField(
                default=0, verbose_name="Total Task Execution Stages"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="uploaded_files",
            field=models.IntegerField(default=0, verbose_name="Files Uploaded to S3"),
        ),
    ]
