# Generated by Django 5.1.3 on 2025-11-23 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dataitem",
            name="cover",
        ),
        migrations.RemoveField(
            model_name="dataitem",
            name="internal_meta",
        ),
        migrations.RemoveField(
            model_name="dataitem",
            name="offline",
        ),
        migrations.RemoveField(
            model_name="dataitem",
            name="offline_size",
        ),
        migrations.RemoveField(
            model_name="dataitem",
            name="sku",
        ),
        migrations.RemoveField(
            model_name="dataitem",
            name="start_file",
        ),
        migrations.RemoveField(
            model_name="dataitem",
            name="storage",
        ),
        migrations.RemoveField(
            model_name="dataitem",
            name="year",
        ),
    ]
