# Generated by Django 5.1.3 on 2025-11-23 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_dataitem_cover_remove_dataitem_internal_meta_and_more'),
        ('reference', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='service',
            new_name='data_type',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='publisher_meta',
            new_name='meta',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='publisher_status',
            new_name='status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='publisher_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='service_item_link',
        ),
        migrations.RemoveField(
            model_name='task',
            name='service_meta',
        ),
        migrations.RemoveField(
            model_name='task',
            name='service_publish_date',
        ),
        migrations.RemoveField(
            model_name='task',
            name='service_response',
        ),
        migrations.RemoveField(
            model_name='task',
            name='service_response_code',
        ),
        migrations.RemoveField(
            model_name='task',
            name='service_status',
        ),
        migrations.RemoveField(
            model_name='task',
            name='total_files',
        ),
        migrations.RemoveField(
            model_name='task',
            name='uploaded_files',
        ),
        migrations.CreateModel(
            name='DatasourceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('response', models.JSONField(blank=True, null=True, verbose_name='Response Body')),
                ('status_code', models.IntegerField(null=True, verbose_name='Status Code')),
                ('headers', models.JSONField(blank=True, null=True, verbose_name='Response Headers')),
                ('datasource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.datasource', verbose_name='Datasource')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='datasource_logs', to='core.task', verbose_name='Publication Task')),
            ],
            options={
                'verbose_name': 'Datasource Log',
                'verbose_name_plural': 'Datasource Logs',
            },
        ),
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('response', models.JSONField(blank=True, null=True, verbose_name='Response Body')),
                ('status_code', models.IntegerField(null=True, verbose_name='Status Code')),
                ('headers', models.JSONField(blank=True, null=True, verbose_name='Response Headers')),
                ('task', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_logs', to='core.task', verbose_name='Publication Task')),
                ('webhook', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.webhook', verbose_name='Webhook')),
            ],
            options={
                'verbose_name': 'Webhook Log',
                'verbose_name_plural': 'Webhook Logs',
            },
        ),
    ]
