# Generated by Django 5.1.3 on 2025-11-24 12:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rename_service_task_data_type_and_more"),
        (
            "reference",
            "0002_pluginrepo_team_workspace_alter_consumer_datasource_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="dataitem",
            name="workspace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reference.workspace",
                verbose_name="Workspace",
            ),
        ),
        migrations.AddField(
            model_name="datasourcelog",
            name="workspace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reference.workspace",
                verbose_name="Workspace",
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="workspace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reference.workspace",
                verbose_name="Workspace",
            ),
        ),
        migrations.AddField(
            model_name="webhooklog",
            name="workspace",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reference.workspace",
                verbose_name="Workspace",
            ),
        ),
    ]
