# Generated by Django 4.1.12 on 2025-11-22 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=512, null=True, verbose_name="Name"),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=512, null=True, verbose_name="Access Key"
                    ),
                ),
                (
                    "validator",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Publication Metadata Validation Model",
                    ),
                ),
            ],
            options={
                "verbose_name": "Source System",
                "verbose_name_plural": "Source Systems",
            },
        ),
        migrations.CreateModel(
            name="SourceContentMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=1024, null=True, verbose_name="Content Type Name"
                    ),
                ),
                (
                    "source_code",
                    models.CharField(
                        max_length=100,
                        null=True,
                        verbose_name="Source System Content Code",
                    ),
                ),
                (
                    "target_code",
                    models.CharField(
                        max_length=100, null=True, verbose_name="Target Content Code"
                    ),
                ),
                (
                    "modifier_module",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Demo Mode Modifier",
                    ),
                ),
                (
                    "link_module",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Unified Collection Link Generator",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reference.source",
                        verbose_name="Source System",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Type",
                "verbose_name_plural": "Content Types",
            },
        ),
        migrations.CreateModel(
            name="Target",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=1024, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "publish_jwt_secret",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Metadata Publishing Secret",
                    ),
                ),
                (
                    "publish_api",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Metadata Publishing API",
                    ),
                ),
                (
                    "unpublish_api",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Unpublishing API",
                    ),
                ),
                (
                    "read_jwt_secret",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Content Reading Secret",
                    ),
                ),
                (
                    "aud",
                    models.CharField(
                        db_index=True,
                        max_length=100,
                        null=True,
                        verbose_name="AUD for Reading JWT Tokens",
                    ),
                ),
            ],
            options={
                "verbose_name": "Target Platform",
                "verbose_name_plural": "Target Platforms",
            },
        ),
        migrations.CreateModel(
            name="TargetStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step",
                    models.IntegerField(default=0, verbose_name="Processing Step"),
                ),
                (
                    "module",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Processing Software Module",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, verbose_name="Processing Stage Active"
                    ),
                ),
                (
                    "target_content",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="target_stages",
                        to="reference.sourcecontentmap",
                        verbose_name="Target Platform",
                    ),
                ),
            ],
            options={
                "verbose_name": "[Target] Processing Stage",
                "verbose_name_plural": "[Target] Processing Stages",
            },
        ),
        migrations.CreateModel(
            name="SourceStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step",
                    models.IntegerField(default=0, verbose_name="Processing Step"),
                ),
                (
                    "module",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Processing Software Module",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, verbose_name="Processing Stage Active"
                    ),
                ),
                (
                    "source_content",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_stages",
                        to="reference.sourcecontentmap",
                        verbose_name="Content Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "[Source] Processing Stage",
                "verbose_name_plural": "[Source] Processing Stages",
                "ordering": ("step",),
            },
        ),
        migrations.AddField(
            model_name="sourcecontentmap",
            name="target",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reference.target",
                verbose_name="Target Platform",
            ),
        ),
    ]
