# Generated by Django 5.1.3 on 2025-11-23 15:44

import django.db.models.deletion
import reference.models
import reference.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DataSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("postgres", "PostgreSQL"), ("duckdb", "DuckDB")],
                        default="postgres",
                        max_length=50,
                        verbose_name="Type",
                    ),
                ),
                (
                    "connection",
                    models.CharField(
                        max_length=2048, null=True, verbose_name="Connection String"
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Source",
                "verbose_name_plural": "Data Sources",
            },
        ),
        migrations.CreateModel(
            name="Source",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=512, null=True, verbose_name="Name"),
                ),
                (
                    "key",
                    models.CharField(
                        max_length=512, null=True, verbose_name="Access Key"
                    ),
                ),
            ],
            options={
                "verbose_name": "Source",
                "verbose_name_plural": "Sources",
            },
        ),
        migrations.CreateModel(
            name="Webhook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        max_length=2048, null=True, verbose_name="Webhook URL"
                    ),
                ),
                (
                    "jwt_secret",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="JWT Secret",
                    ),
                ),
                (
                    "aud",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="AUD"
                    ),
                ),
                (
                    "ttl",
                    models.IntegerField(default=3600, verbose_name="JWT TTL (seconds)"),
                ),
            ],
            options={
                "verbose_name": "Webhook",
                "verbose_name_plural": "Webhooks",
            },
        ),
        migrations.CreateModel(
            name="Consumer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=1024, null=True, verbose_name="Name"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("webhook", "Webhook"), ("datasource", "DataSource")],
                        default="webhook",
                        max_length=50,
                        verbose_name="Type",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Access Key",
                    ),
                ),
                (
                    "datasource",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reference.datasource",
                        verbose_name="DataSource",
                    ),
                ),
                (
                    "webhook",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reference.webhook",
                        verbose_name="Webhook",
                    ),
                ),
            ],
            options={
                "verbose_name": "Consumer",
                "verbose_name_plural": "Consumers",
            },
        ),
        migrations.CreateModel(
            name="DataType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=100, null=True, verbose_name="Name"),
                ),
                (
                    "source_code",
                    models.CharField(
                        max_length=100,
                        null=True,
                        verbose_name="Source System Content Code",
                    ),
                ),
                (
                    "consumer",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reference.consumer",
                        verbose_name="Consumer",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reference.source",
                        verbose_name="Source System",
                    ),
                ),
            ],
            options={
                "verbose_name": "Data Type",
                "verbose_name_plural": "Data Types",
            },
        ),
        migrations.CreateModel(
            name="ProcessingStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "step",
                    models.IntegerField(default=0, verbose_name="Processing Step"),
                ),
                (
                    "module_file",
                    models.FileField(
                        null=True,
                        storage=reference.storage.PipelineStorage(),
                        upload_to=reference.models.pipeline_file_path,
                        verbose_name="Processing Software Module",
                    ),
                ),
                (
                    "active",
                    models.BooleanField(
                        default=True, verbose_name="Processing Stage Active"
                    ),
                ),
                (
                    "data_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="processing_stages",
                        to="reference.datatype",
                        verbose_name="Data Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Processing Stage",
                "verbose_name_plural": "Processing Stages",
                "ordering": ("step",),
            },
        ),
    ]
