# Generated by Django 5.1.3 on 2025-11-23 11:16

import django.db.models.deletion
import reference.models
import reference.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processingstage",
            name="module",
        ),
        migrations.RemoveField(
            model_name="processingstage",
            name="source_content",
        ),
        migrations.RemoveField(
            model_name="source",
            name="validator",
        ),
        migrations.AddField(
            model_name="processingstage",
            name="data_type",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="processing_stages",
                to="reference.datatype",
                verbose_name="Data Type",
            ),
        ),
        migrations.AddField(
            model_name="processingstage",
            name="module_file",
            field=models.FileField(
                null=True,
                storage=reference.storage.PipelineStorage(),
                upload_to=reference.models.pipeline_file_path,
                verbose_name="Processing Software Module",
            ),
        ),
    ]
