# Generated by Django 5.1.3 on 2025-11-24 13:24

import reference.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reference",
            "0002_pluginrepo_team_workspace_alter_consumer_datasource_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="plugin",
            name="file",
            field=models.FileField(
                upload_to=reference.models.plugin_file_path, verbose_name="Plugin File"
            ),
        ),
    ]
