# Generated by Django 5.1.3 on 2025-11-24 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reference", "0003_alter_plugin_file"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="processingstage",
            name="module_file",
        ),
        migrations.AddField(
            model_name="processingstage",
            name="plugin",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="reference.plugin",
                verbose_name="Plugin",
            ),
        ),
    ]
